services:
  - type: web
    name: curves-backend
    env: python
    plan: free
    repo: https://github.com/alejandromya/Curves
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: FLASK_ENV
        value: production
